version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports: 
      - "8020:8080"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/dist
    command: ["docker/app/start.sh"]
